### ISSUE TITLE
Change download folder

### ISSUE THREAD

**Issue by PWDSerialgamer07** [darkdragn/party#1]
Add the ability to change where the tool will download everything.

**Comment by darkdragn** [comment]
I haven't checked GitHub in a while, we just had a baby with a heart condition in November. Sorry, I'll add this tonight! No problem at all, just a quick flag. Now, downloading multiple artists to the same folder would break the update command, just an FYI, since the artist information is stored in .info for the target download directory.

But, I'll have a new release up tonight!

**Comment by NagromW** [comment]
Great shit you've got here @darkdragn , thanks for the update... you're doing gods work - that other guy was pretty demanding but you've got this buddy.

**Comment by darkdragn** [comment]
@NagromW Ask nicely and this is what you get! ;) 
Check out tag v0.5.0 and let me know what you think!

**Comment by NagromW** [comment]
@darkdragn I was actually going to mention the 429 errors I was getting 😅 glad they're being worked on - I think coomer rate limits me though when I try and download... Seems to take forever to open the original images from their website despite having a solid gigabit connection.

**Comment by muggsyd** [comment]
I think you need to add the -d to your README.MD (although I found it thru trial and error)

Is there anyway to add the -d to the "update" functionality?

**Comment by darkdragn** [comment]
Yeah, no problem. (On the first iteration I added it to extra options and attached it to the user schema so update against the custom directory will pull to that folder since update ready the .info in that directory. If there's an issue with that let me know.)

Sorry about the readme, I have a 5 months old so I get some code done then run off to parenting duties. A lot easier than the first time around, though, since I now have a 9 year old to help entertain the little, lol. 

I've also been cutting over to annotations for cli documentation. I need to finish that too, when I started on this project typer was in it's infancy so that feature wasn't available. (I think I just did a dependency update and went from v0.2.0 to v0.9.0) 

Let me know if there's any other features you guys want.

Btw, I've noticed that server side limits seem inconsistent. Some days 4 works get thousands of files with no problem, some days only two worker causes the server to freak out the 429 all over the place

**Comment by muggsyd** [comment]
Sorry I didn't mean to come across as demanding.. Sometimes I am a bit too direct with comments.

In regards to the 429 errors, when I was using **youtube-dl** a lot, that would be generate a lot of 429 errors as well.. to get a round it you could set an option to set a time period between requests,  or randomise that limit as well..

**Comment by darkdragn** [comment]
@JeanKeitwo Sorry, it's in the cli but I haven't gotten around to updating the README. Here's an example:

```
darkdragn@dragnDesk [06:50:55 AM] [/media/dumpCrypt/Documents/src/personal/party] [main *]
-> % party kemono patreon Creux --directory temp --limit 5
2023-11-03 06:50:59.099 | DEBUG    | party.cli:pull_user:91 - Excluded Extensions: []
⠋ User found: creux; parsing posts...Duplicate files found, recommend using post_id
Embedded objects found; saving to temp/.embedded
Downloading from user: creux
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:11<00:00,  1.02s/it]
2023-11-03 06:51:22.814 | INFO     | party.cli:pull_user:176 - Output status: Counter({<StatusEnum.SUCCESS: 1>: 11})                                                                      
darkdragn@dragnDesk [06:51:22 AM] [/media/dumpCrypt/Documents/src/personal/party] [main *]
-> % ls temp
Bex_MediumSupport_1_Twitter.jpg  Bex_YellowJacket_2_Patreon.jpg      LoisLane_StripGame02_1_Twitter.jpg  Splatball_Lucia_1_Twitter.jpg
Bex_MediumSupport_2_Patreon.jpg  LoisLane_StripGame01_1_Twitter.jpg  LoisLane_StripGame02_2_Twitter.jpg  Splatball_Lucia_2_Patreon.jpg
Bex_YellowJacket_1_Twitter.jpg   LoisLane_StripGame01_2_Patreon.jpg  LoisLane_StripGame02_3_Patreon.jpg
```
