### ISSUE TITLE
Download for Windows?

### ISSUE THREAD

**Issue by R3alS1rus** [darkdragn/party#10]
I tried running the commands for installation using cmd on Windows & Windows Power Shell after installing latest release of Phyton but can not get it to even install or run.

**Comment by CodingCoomer** [comment]
Can you give us some more information about what you did specifically? 
Copy and paste from the shell what you typed and what the output was.

**Comment by julesupss** [comment]
My best guess is that python / pip is not added to PATH.

A general guide to install on windows:
1. Download python (latest version (3.11) works at time of writing). Most modern computers are 64-bit so the 64-bit installer should work but if unsure or if the 64-bit doesn't work then install the 32-bit installer.
2. Make sure python is added to the PATH (search up how to do this if you don't know how), though a fresh install of python should have an option to add to PATH during installation.
3. Then the command 'pip install https://github.com/darkdragn/party/releases/download/v0.5.0/party-0.5.0-py3-none-any.whl' should work to install the current latest version
4. Hope this helps.

If you still have a problem please add more information to what the problem is.
