### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by mitchellchris1** [darkdragn/party#23]
`NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'.`

It should be noted that I got this error occurred just recently. I was using it since last month and never got this error before. The command used to work well in the past. If it helps in anything, i am using mac

**Comment by darkdragn** [comment]
So, I did a little research. There's two ways to fix this on mac. Either `brew install openssl@1.1` or I can force a requirement on urllib3<=2.0.0 since all 1.x.x versions don't have a strict openssl dependency. 

I'm cool with doing either, this probably happened because urllib3 released the 2.0 as stable and you got it during an upgrade. But, I'd rather not make a commit and publish a release until you test it and let me know that downgrading urllib3 works for you. Can you run `pip install "urllib3<=2.0.0"` for me, then attempting pulling and let me know what you get? 

If that works, I'll add that dep.

**Comment by mitchellchris1** [comment]
> So, I did a little research. There's two ways to fix this on mac. Either `brew install openssl@1.1` or I can force a requirement on urllib3<=2.0.0 since all 1.x.x versions don't have a strict openssl dependency.
> 
> I'm cool with doing either, this probably happened because urllib3 released the 2.0 as stable and you got it during an upgrade. But, I'd rather not make a commit and publish a release until you test it and let me know that downgrading urllib3 works for you. Can you run `pip install "urllib3<=2.0.0"` for me, then attempting pulling and let me know what you get?
> 
> If that works, I'll add that dep.

I followed your recommendations and executed the commands you provided. Here are the results:

1. I ran the `python3 -m pip install "urllib3<=2.0.0"` command, which resulted in a successful downgrade of urllib3 to version 1.26.18. The installation process went smoothly, and the older version of urllib3 was installed without any issues.

2. Additionally, I used the `python3 -m pip install` command to install the party package from the specified release. This command also executed successfully, and I now have party version 0.6.3 installed in my environment.

These actions appear to have resolved the issue I was facing, and I can now successfully pull the changes without encountering any problems. Thank you for your quick response and the solution provided. I appreciate your help in resolving this issue. If you have any further steps or updates, please feel free to let me know, and I'll be happy to assist.

**Comment by darkdragn** [comment]
Sweet! That's great to hear. I'm working with a rescue puppy right now, so I'll push a hard dependency a little later when I get home and have access to my computer. 

Be on the look out! ;)

**Comment by mitchellchris1** [comment]
That sounds fantastic! I appreciate your flexibility in addressing this, and it's great to hear that things are working smoothly now. Best of luck with your rescue puppy, and I'll certainly be on the lookout for the updates. If you need any further assistance or feedback from my end, please don't hesitate to reach out. 

Thanks again for your help!

**Comment by darkdragn** [comment]
Just pushed the update. v0.6.4 is a published release and has the changes. 

I'm going to close this issue, and since you mentioned probably being able to help, I might ask for one thing... The issue next to this one, #22 has a creator on onlyfans using emoji's in their post titles. The user that reported the error looks like they got an exception during parsing with marshmallow that I couldn't re-create on my Linux nodes. I'm going to test Windows later to see if it was a windows thing, but I don't have a MAC to see if it was maybe a MAC things. 

It you could take a moment to run `party coomer onlyfans vaniitys -e m4v -e mp4 --limit 4 --post-title` and see if you have any errors, I'd appreciate it. You can purge the directory right after that. If you do get an error, please post the full traceback to issue #22 for me, so I know where the encoding error is coming from, and I can work on handling it. I'd really appreciate it!
