### ISSUE TITLE
user found but parsing posts forever ... :(

### ISSUE THREAD

**Issue by MiMmmmiiii** [darkdragn/party#25]
I just use it downloaded one onlyfans and all 129 GB completed perfectly,
but when I want to use the same command to download another one,
it just parsing forever like below:

![2023-11-14_193812](https://github.com/darkdragn/party/assets/20210034/4bfdf9ea-0e75-447e-8c64-d0592eba418d)

changed another target results the same,
changed back to original download path still,
any solution?
Many thanks!!!!!!!

**Comment by darkdragn** [comment]
@MiMmmmiiii I'm going to look into it right now. Might be a quirk with that user... For now, try using the limiting option until I push a patch. 

Oh, btw. I got upto 32 workerd going well since I made some connection handling tweaks and was pulling at over 100Mb last evening! 
![Screenshot 2023-11-12 02 33 53](https://github.com/darkdragn/party/assets/6917732/c38e931c-253c-4688-a0f7-2d49334bef88)


That'll be in the patch too. It isn't the best example, since files were completing so fast, I got the total download speed from watching glances for IO traffic. I might need to tweak up tqdm a bit

**Comment by darkdragn** [comment]
@MiMmmmiiii Oh, and by the limiting option I mean try adding `--limit 100` or change 100 to whatever number of posts you want to limit parsing to. That should stop anything involving infinite api queries going on until I get a patch out.

**Comment by darkdragn** [comment]
@MiMmmmiiii Just found the error. It's a super simple fix. Should be out in the next few minutes.

**Comment by darkdragn** [comment]
Release with the fix is out: v0.6.8

**Comment by MiMmmmiiii** [comment]
Appreciated for your quick help so much!!! :)
