### ISSUE TITLE
Issue downloading only one certain user

### ISSUE THREAD

**Issue by ZachFett** [darkdragn/party#4]
First off, thank you very much for this program, it's incredibly useful!
So far the program is working flawlessly for me for both kemono and coomer.. except for one profile. I'm not sure why, but every time it gives me this message after "Pulling User ID" for a few seconds:
![image](https://github.com/darkdragn/party/assets/29797689/2c1c9c78-3ad6-4e89-9d2e-e507c928ac1d)

I tried both "party coomer 434514358358253568" and "party coomer forgottenlovechild", both give the same issue.

Also side note, is there a way to change the default download directory? I saw that someone else asked about this back in January but didn't see any documentation on how to actually change it, and the last release was in October so I'm assuming it just hasn't been added yet, correct?

**Comment by darkdragn** [comment]
Hey guys!!! I just noticed this issue and I'm going to have it knocked out in just a minute... I just need to send my daughter upstairs so she doesn't see the site while I checkout the new options for coomer. >_< 

Sorry it took me so long to respond. I just saw the e-mails for this issue. Also, thanks for pointing out that I forgot to push that download directory change. I have it made and on my home server, but I blanked on pushing to github since I was traveling when I made the change. Be on the look out for an update in the next hour or so!

**Comment by darkdragn** [comment]
Just finished, pushing now. Previously coomer only supported onlyfans so I hardcoded the service, but I just updated that as an argument and added onlyfans as it's own argument:

```bash
-> % party coomer fansly forgottenlovechild
2023-06-14 14:02:08.758 | DEBUG    | party.cli:pull_user:53 - Ignored Extensions: ()
Downloading from user: forgottenlovechild
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 102/102 [00:21<00:00,  4.85it/s]
2023-06-14 14:02:36.109 | INFO     | party.cli:pull_user:118 - Output status: Counter({<StatusEnum.SUCCESS: 1>: 102}) 
```

Just an fyi, even before this patch you could've run this as a pull command, specified the --site switch with fansly as the service.
